"""
半自动 PR 草稿生成器。

闭环：人工 ✋ approve → 调本服务 → git checkout 新分支 → 写修复说明 markdown
     → commit → push → gh pr create --draft → 写回 crash_pull_requests

🚫 严禁调用：gh pr merge / git merge / gh pr ready —— 永远只创建 draft。
"""
from __future__ import annotations

import logging
import os
import re
import subprocess
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, Optional

from sqlalchemy import select

from app.crashguard.config import get_crashguard_settings
from app.crashguard.models import CrashAnalysis, CrashIssue, CrashPullRequest
from app.db.database import get_session

logger = logging.getLogger("crashguard.pr_drafter")


_FORBIDDEN_FLAGS = ("--merge", "merge", "ready", "--rebase", "--squash")


def _platform_repo_path(platform: str) -> Optional[str]:
    """根据 platform 返回 repo 绝对路径。flutter→repo_path_flutter，回落 jarvis code_repo_app。"""
    s = get_crashguard_settings()
    p = (platform or "").strip().lower()
    direct = {
        "flutter": s.repo_path_flutter,
        "android": s.repo_path_android,
        "ios": s.repo_path_ios,
    }.get(p, "")
    raw = direct
    if not raw:
        # fallback to jarvis 全局 app repo（Plaud2 monorepo 场景）
        from app.config import get_code_repo_for_platform
        raw = get_code_repo_for_platform("app") or ""
    if not raw:
        return None
    return os.path.expanduser(raw)


def _safe_branch_name(issue_id: str, platform: str) -> str:
    short = re.sub(r"[^a-zA-Z0-9]", "", issue_id)[:8] or "noid"
    ts = datetime.utcnow().strftime("%Y%m%d%H%M")
    return f"crashguard/{platform.lower()}/{short}-{ts}"


def _run_git(cmd: list[str], cwd: str, timeout: int = 60) -> tuple[int, str, str]:
    for f in cmd:
        if any(b in f for b in _FORBIDDEN_FLAGS):
            return 1, "", f"forbidden flag in cmd: {f}"
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except subprocess.TimeoutExpired:
        return 1, "", f"timeout after {timeout}s"
    except Exception as e:
        return 1, "", str(e)


def _build_pr_body(issue: CrashIssue, ana: CrashAnalysis, frontend_url: str) -> str:
    """拼装 PR description（markdown）。"""
    lines = [
        f"## Crashguard 半自动 PR — {issue.platform or 'unknown'}",
        "",
        f"**Issue**: `{issue.datadog_issue_id}`",
        f"**Title**: {issue.title or ''}",
        f"**Frontend**: {frontend_url}",
        f"**Confidence**: {ana.confidence or 'low'}  ·  **Feasibility**: {ana.feasibility_score:.2f}",
        "",
        "### 根因",
        ana.root_cause or "_(空)_",
        "",
        "### 修复建议",
        ana.fix_suggestion or ana.solution or "_(空)_",
    ]
    if (ana.fix_diff or "").strip():
        lines += ["", "### Patch", "```diff", ana.fix_diff.strip(), "```"]
    lines += [
        "",
        "---",
        "🤖 Generated by Crashguard. **DO NOT auto-merge** — manual review + approve required.",
    ]
    return "\n".join(lines)


def _build_fix_doc(issue: CrashIssue, ana: CrashAnalysis, frontend_url: str) -> str:
    """生成 docs/crashguard-fixes/<issue>.md 内容（避免直接改源码出错）。"""
    return _build_pr_body(issue, ana, frontend_url) + "\n"


async def draft_pr_for_analysis(
    analysis_id: int,
    approver: str = "human",
    dry_run: bool = False,
) -> Dict[str, Any]:
    """
    入口：根据 analysis_id 生成 draft PR。

    返回：{ok, pr_url?, branch_name?, dry_run?, error?}
    """
    s = get_crashguard_settings()
    if not s.pr_enabled:
        return {"ok": False, "error": "pr_disabled"}

    async with get_session() as session:
        ana = (await session.execute(
            select(CrashAnalysis).where(CrashAnalysis.id == analysis_id)
        )).scalar_one_or_none()
        if ana is None:
            return {"ok": False, "error": f"analysis {analysis_id} not found"}
        if ana.status != "success":
            return {"ok": False, "error": f"analysis status={ana.status}, not success"}
        if not (ana.fix_suggestion or ana.solution or ana.fix_diff):
            return {"ok": False, "error": "no fix content (fix_suggestion/solution/fix_diff all empty)"}

        issue = (await session.execute(
            select(CrashIssue).where(CrashIssue.datadog_issue_id == ana.datadog_issue_id)
        )).scalar_one_or_none()
        if issue is None:
            return {"ok": False, "error": f"issue {ana.datadog_issue_id} not found"}

        # 30 天去重
        since = datetime.utcnow() - timedelta(days=s.pr_dedup_days)
        existing = (await session.execute(
            select(CrashPullRequest).where(
                CrashPullRequest.datadog_issue_id == ana.datadog_issue_id,
                CrashPullRequest.repo == (issue.platform or "").lower(),
                CrashPullRequest.created_at >= since,
            )
        )).scalars().first()
        if existing is not None and not dry_run:
            return {
                "ok": False,
                "error": f"dup_within_{s.pr_dedup_days}d",
                "existing_pr_url": existing.pr_url,
                "existing_branch": existing.branch_name,
            }

    platform = (issue.platform or "").lower()
    repo_path = _platform_repo_path(platform)
    if not repo_path or not Path(repo_path).exists():
        return {"ok": False, "error": f"repo_path not configured/found for platform={platform}"}

    branch = _safe_branch_name(ana.datadog_issue_id, platform)
    frontend_url = f"{s.frontend_base_url.rstrip('/')}/crashguard?issue={ana.datadog_issue_id}"
    pr_body = _build_pr_body(issue, ana, frontend_url)
    pr_title = f"[Crashguard][{platform}] {(issue.title or 'crash fix')[:80]}"
    fix_doc_relpath = f"docs/crashguard-fixes/{ana.datadog_issue_id}.md"
    fix_doc_content = _build_fix_doc(issue, ana, frontend_url)
    commit_message = f"docs(crashguard): draft fix for {ana.datadog_issue_id}\n\n{pr_title}"

    if dry_run:
        return {
            "ok": True,
            "dry_run": True,
            "branch_name": branch,
            "pr_title": pr_title,
            "pr_body_preview": pr_body[:600],
            "fix_doc_relpath": fix_doc_relpath,
            "repo_path": repo_path,
        }

    # === 真实操作：分支 → 写文件 → commit → push → gh pr create --draft ===
    rc, _, err = _run_git(["git", "fetch", "origin"], repo_path, timeout=60)
    if rc != 0:
        return {"ok": False, "error": f"git fetch failed: {err}"}

    rc, _, err = _run_git(["git", "checkout", "-b", branch, "origin/main"], repo_path, timeout=30)
    if rc != 0:
        # 可能是分支已存在 / origin/main 不存在 → 试 master
        rc2, _, err2 = _run_git(["git", "checkout", "-b", branch, "origin/master"], repo_path, timeout=30)
        if rc2 != 0:
            return {"ok": False, "error": f"git checkout failed: main={err}; master={err2}"}

    doc_abs = Path(repo_path) / fix_doc_relpath
    doc_abs.parent.mkdir(parents=True, exist_ok=True)
    doc_abs.write_text(fix_doc_content, encoding="utf-8")

    rc, _, err = _run_git(["git", "add", fix_doc_relpath], repo_path)
    if rc != 0:
        return {"ok": False, "error": f"git add failed: {err}"}
    rc, _, err = _run_git(
        ["git", "commit", "-m", commit_message, "--no-verify"], repo_path, timeout=30,
    )
    if rc != 0:
        return {"ok": False, "error": f"git commit failed: {err}"}
    rc, _, err = _run_git(
        ["git", "push", "-u", "origin", branch], repo_path, timeout=120,
    )
    if rc != 0:
        return {"ok": False, "error": f"git push failed: {err}"}

    # gh pr create --draft（硬编码 --draft）
    rc, stdout, err = _run_git(
        [
            "gh", "pr", "create",
            "--draft",
            "--title", pr_title,
            "--body", pr_body,
            "--head", branch,
        ],
        repo_path,
        timeout=120,
    )
    if rc != 0:
        return {"ok": False, "error": f"gh pr create failed: {err}", "branch_name": branch}
    pr_url = stdout.strip().splitlines()[-1] if stdout else ""
    pr_number = None
    m = re.search(r"/pull/(\d+)", pr_url)
    if m:
        pr_number = int(m.group(1))

    async with get_session() as session:
        row = CrashPullRequest(
            analysis_id=analysis_id,
            datadog_issue_id=ana.datadog_issue_id,
            repo=platform,
            branch_name=branch,
            pr_url=pr_url,
            pr_number=pr_number,
            pr_status="draft",
            triggered_by="human_approved",
            approved_by=approver or "human",
            approved_at=datetime.utcnow(),
            created_at=datetime.utcnow(),
        )
        session.add(row)
        await session.commit()

    logger.info("crashguard draft PR created: %s (analysis=%d)", pr_url, analysis_id)
    try:
        from app.crashguard.services.audit import write_audit
        await write_audit(
            op="pr_draft",
            target_id=str(analysis_id),
            success=True,
            detail={"pr_url": pr_url, "branch": branch, "approver": approver},
        )
    except Exception:
        pass
    return {
        "ok": True,
        "pr_url": pr_url,
        "pr_number": pr_number,
        "branch_name": branch,
    }
